minimum_pre_commit_version: "3.4.0"

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Make sure to use a recent rev
    rev: v0.7.0
    hooks:
      # Hook 1: Run linting, auto-fixing, and import sorting
      - id: ruff
        args: ["--fix"]
      # Hook 2: Run formatting (replaces Black)
      - id: ruff-format
